### ISSUE TITLE
space to spacing?

### ISSUE THREAD

**Issue by himorin** [w3c/simple-ruby#20]
Word "space" is often used in the document, but most of these might be "spacing", similar to https://github.com/w3c/jlreq/issues/85.

**Comment by kidayasuo** [comment]
is the issue just in English translation?

**Comment by himorin** [comment]
is a choice of English word for "空き量", so just in English translation.

**Comment by kidayasuo** [comment]
got it. thanks.

**Comment by himorin** [comment]
close this per #27
