### ISSUE TITLE
unify lay over / hang over

### ISSUE THREAD

**Issue by himorin** [w3c/simple-ruby#23]
two words, lay over or hang over, are used for one meaning - to place protruding characters of ruby text from base string over/under preceding or following text.

**Comment by r12a** [comment]
Not having looked at the context, i offer this advice:

'lay over' sounds wrong, as does 'lie over'.

'to hang over' may be less appropriate and more prone to problems of clarity than 'to overhang', except in some special cases.

**Comment by r12a** [comment]
Closing, since this was addressed in https://github.com/w3c/simple-ruby/pull/34.
