### ISSUE TITLE
More comments from Myles

### ISSUE THREAD

**Issue by r12a** [w3c/simple-ruby#46]
Copied here from email, and numbered to facilitate discussion.

1. Background: why do we need a simple model? Why not just use what’s in JISX/JLREQ? It says the audience is spec writers/implementors, but why wouldn’t they just read the complicated specs instead of this document?
2. An example where the ruby annotation is latin and has descenders would be helpful. Do the descenders descend down into the ruby base area?
3. Probably worth pointing out in section 3.2 (maybe point 3) that mono-ruby always has exactly a single character in its base
4. When adding space for a long ruby annotation, what about character grid?
5. Mono-ruby section talks about what happens when there’s punctuation before/after the base. What about punctuation in the annotation? In the base itself?
6. How do I know which parts are requirements vs which parts are simplifications from the more complicated specs?
I think mono-ruby is a special case of group ruby. I think they’re the same algorithm.
7. For jukugo-ruby, probably should explicitly say that line breaking opportunities are dictated only by the base text, rather than the annotation text.
8. I don’t think jukugo-ruby is actually a two-pass algorithm as defined here, because of line-breaking. The document claims it’s a two-pass algorithm.
9. Section 4.2 lists jukugo-ruby in two of the combinations, but none of the later sections describe how to place any double-sided combinations with jukugo
10. "NOTE: Space between adjacent lines and double-sided ruby” seems normative, I’m not sure why it’s a note
Why are the items in section 2.2 a list?

I suspect that we can answer some of these now, but may want to defer addressing others for the next iteration of the document.

**Comment by xfq** [comment]
> 1. Background: why do we need a simple model? Why not just use what’s in JISX/JLREQ? It says the audience is spec writers/implementors, but why wouldn’t they just read the complicated specs instead of this document?

I am not quite clear about the background of this document, but I think at least one of the reasons for writing this document is to document the most common requirements and let implementers implement high-priority requirements first. There are also some explanations in the simple-ruby document:

> [JLREQ] is largely a record of Japanese layout as established for the printing industry. It explains multiple ways to achieve one thing, and sometimes these approaches can be very complex. Ruby is one such case. There are so many factors to consider, and often contradictory requirements (see some examples), leading to a complexity that makes it challenging to automate ruby.

**Comment by xfq** [comment]
> 9. Section 4.2 lists jukugo-ruby in two of the combinations, but none of the later sections describe how to place any double-sided combinations with jukugo

It’s mentioned in [§ 4.3 Combinations of ruby types and placement methods](https://w3c.github.io/simple-ruby/#rules-for-placement-of-double-sided-ruby-per-combinations):

> We propose to handle (4) as (1) by first converting jukugo-ruby to mono-ruby, and to handle (5) as (2) by first converting jukugo-ruby to group-ruby.

We can improve it if it’s not clear enough.

**Comment by xfq** [comment]
> "NOTE: Space between adjacent lines and double-sided ruby” seems normative, I’m not sure why it’s a note

Because it is a note in the original Japanese text, but I personally feel that this should be included in the main text and can be placed at the end of the section.

> Why are the items in section 2.2 a list?

Since it is a list in the original Japanese text, and every list item is considered a "consideration".

**Comment by himorin** [comment]
>     3. Probably worth pointing out in section 3.2 (maybe point 3) that mono-ruby always has exactly a single character in its base

Defined in section 2.3, but re-mentioning 'exactly a single character' in point 3 could help readers for clear reasoning.

>     4. When adding space for a long ruby annotation, what about character grid?

Something in addition to figure 14?

>     5. Mono-ruby section talks about what happens when there’s punctuation before/after the base. What about punctuation in the annotation? In the base itself?

Some sentence with punctuation could be considered as interlinear notes (there is still [active discussion thread](https://lists.w3.org/Archives/Public/public-i18n-japanese/2020JulSep/0025.html) on difference / boundary between ruby/furigana and interlinear notes, and [interim summary](https://lists.w3.org/Archives/Public/public-i18n-japanese/2020JulSep/0064.html) was proposed but no clear consensus yet), and Note `Note: Ruby and interlinear notes` states this document does not cover interlinear note.

>     6. How do I know which parts are requirements vs which parts are simplifications from the more complicated specs?
>        I think mono-ruby is a special case of group ruby. I think they’re the same algorithm.

(my understanding is this document proposes a set of simple spec as simplifications from the more complicated specs...)
section 3.3 describes about group-ruby as extension from mono-ruby, and [point 4](https://w3c.github.io/simple-ruby/#l20200529034) refers mono-ruby. We might be better to reconsider order of points, points 1 to 3 are description for one set of cases, but points 4 and 5 are general..

>     7. For jukugo-ruby, probably should explicitly say that line breaking opportunities are dictated only by the base text, rather than the annotation text.

point 3 notes `With jukugo-ruby, individual base texts and their associated ruby annotations are treated as a unit, and line wrap opportunities are allowed between two base texts.`.

>     8. I don’t think jukugo-ruby is actually a two-pass algorithm as defined here, because of line-breaking. The document claims it’s a two-pass algorithm.

(I personally agree with this.. line breaking need to come before two-pass)

**Comment by himorin** [comment]
> > Why are the items in section 2.2 a list?
> 
> Since it is a list in the original Japanese text, and every list item is considered a "consideration".

Also we desired to refer items in following sections for their background concept.

**Comment by xfq** [comment]
> > 5. Mono-ruby section talks about what happens when there’s punctuation before/after the base. What about punctuation in the annotation? In the base itself?

> Some sentence with punctuation could be considered as interlinear notes (there is still [active discussion thread](https://lists.w3.org/Archives/Public/public-i18n-japanese/2020JulSep/0025.html) on difference / boundary between ruby/furigana and interlinear notes, and [interim summary](https://lists.w3.org/Archives/Public/public-i18n-japanese/2020JulSep/0064.html) was proposed but no clear consensus yet), and Note `Note: Ruby and interlinear notes` states this document does not cover interlinear note.

I wonder if something like this exists in Japanese: https://github.com/w3c/type-samples/issues/94

It doesn't appear often in Chinese text, but it is used in some textbooks for foreigners/children. It is a bit like 総ルビ in Japanese, but also has punctuation (and letter case) in the annotation (so it is also a bit like interlinear notes). For more information, see [clreq § 3.3.4.3 Words as the Basic Units for Annotating Pronunciation](https://w3c.github.io/clreq/#h-words_as_basic_units_for_annotating_pronunciation).

**Comment by himorin** [comment]
Looking around, but I see nothing... Usual Japanese text are consisted with both kanji and kana (usually hiragana), and even in [general-ruby](https://www.w3.org/TR/jlreq/#id224) way, furigana (ruby annotation) are assigned only to kanji characters but not including kana... - since there is almost no mean to assign furigana (in kana) over kana parts.
@kidayasuo do you know any example that furigana / ruby annotations are assigned to every base text??

**Comment by xfq** [comment]
That makes sense. Thank you @himorin.

**Comment by kidayasuo** [comment]
> @kidayasuo do you know any example that furigana / ruby annotations are assigned to every base text??

No. I have not seen, at least I do not remember, the case where ruby are assigned to every single kana characters. It does not make sense…

**Comment by macnmm** [comment]
As for jukugo-ruby being two-pass or not, consider that the width of the ruby annotated run could increase due to overhang rules -- if the overhanging character wraps and the long jukugo ruby now has to compress differently (or be re-calculated now that it is at line end), that is the second pass, isn't it?

**Comment by murata2makoto** [comment]
I think that the two-pass procedure is just a reference model for making the semantics clear.  One-pass algorithms might be possible, but they are outside the scope of this note.

**Comment by himorin** [comment]
@murata2makoto not one or two pass, but what original comment 8 craims and @macnmm 's point seem to be that there is a possible rework during second pass (NEED well defined wording... though) back to first pass, when a block of jukugo-ruby (built by first pass) runs over an end of line.
for @macnmm 's point of compress differently, placement at the line edge does not change anything inside block(s) of jukugo-ruby (as defined in both 5. in mono- and 3. in jukugo- ruby), and I believe it is not 'differently'.

**Comment by macnmm** [comment]
As for not differently compressing, consider a 3 ruby kanji breaking so the ruby which overhung the broken next kanji now makes the base text wider than before. If it cannot overhang the previous character it could result in a different line width and line break than the one calculated when the ruby overhung the next character. A second pass could detect this and make adjustments. ?

**Comment by himorin** [comment]
I suppose we finally opened PRs to every items listed in wide review comment:

- item 1: #70
- item 2: figure 7 of #62 
- item 3: #63 
- item 4: figure 15 of #62 
- item 5: #69 
- item 6: #64 
- item 7: #75 
- item 8: #75 
- item 9: #58 
- item 10: #73

**Comment by himorin** [comment]
per list in https://github.com/w3c/simple-ruby/issues/46#issuecomment-978749207, all relevant PRs have merged.
@kidayasuo  close this?

**Comment by kidayasuo** [comment]
Let’s close.

Some of the comments from Myles might also be helpful for improving [the descriptions in jlreq-d](https://github.com/w3c/jlreq-d/blob/gh-pages/drafts/%E3%83%AB%E3%83%93%E3%81%AE%E7%B5%84%E7%89%88%E5%87%A6%E7%90%86.md). Would it be possible to close the original and duplicate it in jlreq-d?

**Comment by himorin** [comment]
closing per comment.
@kidayasuo I suppose comments on ruby handling strategy are addressed into Japanese document also, but agree we should check also. Original description of this issue itself is a copy from email, so we can just copy text into new issue in jlreq-d?
