### ISSUE TITLE
Add note "グループ ルビと欧文用間隔" into English version also

### ISSUE THREAD

**Issue by himorin** [w3c/simple-ruby#53]
Check whether the note is not included really in the English version, and also add translated text into appropriate position.

**Comment by xfq** [comment]
It seems to be missing in [§ 3.3 Placement of group-ruby](https://w3c.github.io/simple-ruby/#placement-of-group-ruby).

**Comment by xfq** [comment]
The original Japanese note is:

> グループルビと欧文用間隔

> グループルビの親文字列又はルビ文字列に欧文用間隔（cl-26）を含む場合もあるが，ここでは適用範囲外とした．文字列の長さをそろえる調整に使用する方法と使用しない方法がある．JIS X 4051 では文字列の長さの調整に使用しない方法を規定している．

My trial translation:

> Group ruby and Western word space

> There are cases in which the base characters or the ruby characters of group-ruby include Western word spaces (cl-26), but they are out of scope for this document. There are methods unifying or not unifying the length of the base and ruby characters. The method defined in JIS X 4051 does not unify the length of the base and ruby characters.
