### ISSUE TITLE
update text for #46 point 1 (C-#46-1)

### ISSUE THREAD

**Issue by himorin** [w3c/simple-ruby#59]
from https://lists.w3.org/Archives/Public/public-i18n-japanese/2021OctDec/0088.html

Add following text at the end of the last paragraph in section 2.1

> そのためには，かなり複雑な処理となる（例：JLRrqの付属書“F　熟語ルビの配置⽅法”）．しかし，この方法でもいくつかの問題は残る．そこで，ある程度の品質を確保しながら，機械的な処理に対応した単純化した処理方法を検討する意味はある．以下は，そのひつとの処理方法の提案である．

proposed English text (replacing the last sentence):

> Considering all the possibilities that existed in movable type typesetting, the system to be designed needs to be very complex, for example <a data-cite="JLREQ#positioning_of_jukugoruby">[JLREQ] Appendix F. Positioning of Jukugo-ruby</a>. Although using such complex rules, several issues on placement of ruby. Therefore, it's worth to consider a simple method of ruby composition for computer-based typesetting with securing some degree of quality. The following is a proposal for a simple processing system.

**Comment by murata2makoto** [comment]
This issue appears to address [the first comment](https://github.com/w3c/simple-ruby/issues/46#issuecomment-674031300) by @r12a.

**Comment by macnmm** [comment]
これはどうでしょうか。
If we were to consider all the possibilities that existed in movable type typesetting, the algorithm required would be extremely complex, for example in JLReq appendix F Positioning of Jukugo Ruby. Moreover, even using such complex rules, several issues remain with placement of ruby. Therefore it seems worth it to consider a simpler method of ruby composition for computer-based typesetting that still results in relatively high quality. The following is a proposal for a simpler processing system.

**Comment by himorin** [comment]
@macnmm please review or comment at PR #70
