### ISSUE TITLE
Add five notes to rules for simple placement section C-#46-6

### ISSUE THREAD

**Issue by himorin** [w3c/simple-ruby#60]
from https://lists.w3.org/Archives/Public/public-i18n-japanese/2021OctDec/0097.html

Add three notes right after text of 3.2 (mono-ruby), and add one note each right after text of 3.3 (group-ruby) and 3.4 (jukugo-ruby). These notes are to describe what points were simplified from more complex considerations.

**Comment by xfq** [comment]
I tried to translate the first two notes when reading them. Feel free to reuse/modify my translation.

### Simplification of mono-ruby 1

In mono-ruby, the following are the main methods of deciding the relative positions of the ruby annotation and its base text. In this document, option 1 is used. The ruby annotations are set solid.

1. Align the center of the base text with the center of the ruby annotation.
2. Align the beginning of the base text with the beginning of the ruby annotation.
3. In principle, the beginning of the base text and the beginning of the ruby annotation are aligned, but if the length of the ruby annotation is longer than that of the base character, the ruby annotation extends beyond its base text. The results are adjusted depending on the class of the characters preceding and following.

### Simplification of mono-ruby 2

When the ruby annotation is wider than its base text, the following are the main methods of deciding whether it can be allowed to overhang the characters preceding or following. In this document, option 1 is used. This simplification is the same for group-ruby and jukugo-ruby.

1. Do not overhang neighboring characters, except for punctuation marks with a blank portion.
2. Do not overhang neighboring kanji, but allow ruby characters to overhang kana and some punctuation marks by 1/2 of the base character size.
3. Allow ruby characters to overhang the characters preceding and following the base character by 1/4 of the base character size regardless of the character class.

**Comment by KobayashiToshi** [comment]
モノルビの簡略化3は，以下に修正【】が修正箇所

モノルビの簡略化3　親文字からルビ文字列がはみ出した場合，【行頭及び行末の】配置の主なものとして以下のような方法がある．ここでは1を採用した．2の場合には，簡略化1で採用した配置方法を変更しないといけない．この簡略化は，グループルビ，熟語ルビの場合で同じである．
1　行頭ではルビ文字列の先頭，【行末でも】ルビ文字列の末尾をそろえる．
2　行頭では親文字の先頭，【行末でも】親文字の末尾をそろえる．

**Comment by KobayashiToshi** [comment]
熟語ルビの簡略化は，以下でお願い．【】内が修正箇所

熟語ルビの簡略化　熟語ルビでは，主なものとして以下のような方法がある．ここでは1を採用した．2又は3の処理法は簡略であるが，熟語ルビの性質から，あるいは，ルビと親文字の対応方法を変えれば，この方法は採用できることから，採用しなかった．
1　熟語ルビを構成する各親文字に対応するルビの文字列の長さにより，各親文字に対応するルビをモノルビで処理するか，又は熟語ルビ全体をグループルビとして処理する．
2　熟語ルビを構成する各親文字に対応するルビの組み合わせにより，それぞれをモノルビとして処理する．
3　熟語ルビ全体をグループルビとして処理する．
4　熟語内では，各親文字と対応しないルビについて，その前後の漢字に親文字サイズで1/2まで掛かってよいとする処理を行う．この方式では，親文字列からのルビのはみ出しは，モノルビで説明した【簡略化1の3】の方法による．他にも，細かいルールがある．

**Comment by macnmm** [comment]
I think we need some examples of “real” ruby layout (complex rules) compared to the above simple rules, so implementers can know the tradeoffs. These rules seem to me to be a quality compromise so ruby can be supported more widely.

**Comment by himorin** [comment]
@macnmm there are some example images in a note placed at introduction
https://www.w3.org/TR/simple-ruby/#n20200529002

we may add some example images into appendix added by #64 , but I don't think that is necessity. (or, one can check JLReq for pseudo full archive of variations, as mentioned in simple-ruby introduction...)
