### ISSUE TITLE
Replace the last sentence of section 3.1 (B-#46-3)

### ISSUE THREAD

**Issue by himorin** [w3c/simple-ruby#61]
from https://lists.w3.org/Archives/Public/public-i18n-japanese/2021OctDec/0104.html

New Japanese text proposed, so replace the last sentence of section 3.1 with a new text.

**Comment by xfq** [comment]
This text looks good to me, but for readers who go directly to section 3.2, I'm afraid they won't see the last sentence of section 3.1...

What about adding a link to https://w3c.github.io/simple-ruby/#types-of-ruby in section 3.2?

**Comment by himorin** [comment]
Rather than just adding a link to other section, I would personally propose to use dfn/a-title for technical wording. Some could state that we should be better to refer terminology in JLReq, although (we may have a link at the dfn position?)...
