### ISSUE TITLE
wrong English phrase in "Ruby character size and character placement"

### ISSUE THREAD

**Issue by himorin** [w3c/simple-ruby#71]
In section "Ruby character size and character placement", leading sentence is 

> The size of the ruby characters and their placement in the inline direction relative to the base characters is as follows:

but `inline direction` should be `block direction`, since this part discusses about linefeed.

**Comment by Manoj0Marmat** [comment]
@himorin sir can i help ?

**Comment by himorin** [comment]
Although it seems conflicting with #57, checked the subsection and proposed text as PR. (could require rebase or update).
