### ISSUE TITLE
Correct the PDF

### ISSUE THREAD

**Issue by KobayashiToshi** [w3c/simple-ruby#79]
PDFを修正いたしました．2022,4.03
[ルビ簡便ルール4_03.pdf](https://github.com/w3c/simple-ruby/files/8403773/4_03.pdf)

**Comment by himorin** [comment]
@KobayashiToshi 2_27版もグレースケールでPDF生成されているのですが、初版からカラーでなくグレースケールなので意図通り、という認識で大丈夫でしょうか？ (confirming whether to publish PDF in gray or color)

**Comment by KobayashiToshi** [comment]
>2_27版もグレースケールでPDF生成されているのですが、初版からカ
>ラーでなくグレースケールなので意図通り、という認識で大丈夫でしょうか？ 

Webではカラーは費用がかからないが，紙を前提の場合，どうしてもモノクロの意識が強く，そうしています．また，このドキュメントでは，カラーでなくても表現できますので．
なお，Web用の#81のファイルは，PDFとはファイルとは異なるものです．

**Comment by KobayashiToshi** [comment]
>カッコの中の部分は、注釈「2レベルの処理方式」の文章とまとめてしまった方が
>すっきりするような気がするのですが、いかがでしょうか？

PDF修正いたしました．ただし，“2レベルの処理方式”と一緒にするとつながりがよくないので，“複雑なルビ処理例”として別建ての注記にしました．
[ルビ簡便ルール3_01.pdf](https://github.com/w3c/simple-ruby/files/8159387/3_01.pdf)
