### ISSUE TITLE
check inconsistent terminology (esp. ruby base / ruby annotation)

### ISSUE THREAD

**Issue by himorin** [w3c/simple-ruby#88]
before finalizing as note, re-check terminology.

see also https://github.com/w3c/jlreq/wiki/English-ruby-terminology

**Comment by himorin** [comment]
also we could remove title="" from `<a>` links, e.g. ones for mono-ruby, jukugo-ruby, or group-ruby.

**Comment by himorin** [comment]
- Check words are using American ones (e.g. center),  esp. changes made through grammarly.com configuration of @kidayasuo 
- Check links to JLreq are correct or not, esp. cl-XX ones which have already found

**Comment by kidayasuo** [comment]
Let’s close.

**Comment by himorin** [comment]
closing per comment.
